### ISSUE TITLE
Disconnecting issues

### ISSUE THREAD

**Issue by jhhernan** [aderusha/HASwitchPlate#103] opened 2020-04-21 14:54 UTC
Hi. First of all: Congratulations! Great job, its a very useful proyect.
I updated to the last version but I`ve been noticing some disconnections. What can I check?
I have another HASwitchPlate with the older verson and it`s working OK.

**Comment by aderusha** [comment] 2020-05-20 10:48
For testing purposes you can revert to an older firmware if you think that's the issue.  Is there any chance the issue is RF signal related?  Can you maybe swap the location of the two devices?

**Comment by aderusha** [comment] 2020-12-19 15:00
Closing after no update from submitter

**Closed as completed by aderusha** 2020-12-19 15:00 UTC
